apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.hermes.cm }}
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  traffic.json: |
    {
      "dns": "{{ .Values.global.hermes.endpoint | default .Values.endpoint }}",
      "port": "{{ .Values.global.hermes.port | default .Values.port }}",
      "timeout": {{ .Values.global.hermes.timeout | default .Values.timeout }},
      "ranges": {
        "range_1": {
          "min": 0,
          "max": 999999
        }
      },
      "flow": [
        "{{ .Release.Name }}-post",
        "{{ .Release.Name }}-post"
      ],
      "messages": {
        "{{ .Release.Name }}-post": {
          "method": "POST",
          "url": "url/example/path/id-<range_1>",
          "body": {
            "field1": "id-<range_1>-suffix",
            "field2": "some_stuff",
            "field3": {
              "sub_field1": 0,
              "subfield2": "some_string"
            }
          },
          "response": {
            "code": 200
          }
        }
      }
    }


