{
 "title": "Kepler Exporter Dashboard",
 "description": "Dashboard for Kepler Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "watt_per_second_to_kWh", "query": "0.000000277777777777778" }
  ]
 },
 "panels": [
  {
   "title": "Real time Power consumption (W)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kepler_container_joules_total{container_namespace=~\"serverless-ns|knative-serving|knative-serving-ingress|openshift-serverless\"}[1m]))",
     "legendFormat": "serverless"
    },
    {
     "expr": "sum(rate(kepler_container_joules_total{container_namespace=~\"serverfull-ns|istio-system\"}[1m]))",
     "legendFormat": "serverfull"
    }
   ]
  },
  {
   "title": "ServerfullRequests/s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(hermes_requests_sent_total{id=\"serverfull-post\"}[1m]))"
    }
   ]
  },
  {
   "title": "Serverless Requests/s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(hermes_requests_sent_total{id=\"serverless-post\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(hermes_requests_sent_total{id=\"serverless-post\"}[5m]))",
     "legendFormat": "Serverless"
    },
    {
     "expr": "avg(rate(hermes_requests_sent_total{id=\"serverfull-post\"}[5m]))",
     "legendFormat": "Serverfull"
    }
   ]
  },
  {
   "title": "Serverless real time Power consumption (W)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (container_namespace) (rate(kepler_container_joules_total{container_namespace=~\"serverless-ns|knative-serving|knative-serving-ingress|openshift-serverless\"}[1m]))",
     "legendFormat": "{{ container_namespace }}"
    },
    {
     "expr": "sum(rate(kepler_container_joules_total{container_namespace=~\"serverless-ns|knative-serving|knative-serving-ingress|openshift-serverless\"}[1m]))",
     "legendFormat": "Total serverless"
    }
   ]
  },
  {
   "title": "Serverless Total Energy Consumption (kWh) $__range",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(kepler_container_joules_total{container_namespace=~\"serverless-ns|knative-serving|knative-serving-ingress|openshift-serverless\"}[$__range:10s])) * 0.000000277777777777778"
    }
   ]
  },
  {
   "title": "Serverfull real time Power consumption (W)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (container_namespace) (rate(kepler_container_joules_total{container_namespace=~\"serverfull-ns|istio-system\"}[1m]))",
     "legendFormat": "{{ container_namespace }}"
    },
    {
     "expr": "sum(rate(kepler_container_joules_total{container_namespace=~\"serverfull-ns|istio-system\"}[1m]))",
     "legendFormat": "Total serverfull"
    }
   ]
  },
  {
   "title": "Serverfull+Istio Energy Consumption (kWh) $__range",
   "type": "stat",
   "description": "Namespaces: serverfull-ns|istio-system",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(kepler_container_joules_total{container_namespace=~\"serverfull-ns|istio-system\"}[$__range:15s])) * 0.000000277777777777778"
    }
   ]
  },
  {
   "title": "Energy consumption (kWh) (per $__range)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(kepler_container_joules_total{container_namespace=~\"serverless-ns|knative-serving|knative-serving-ingress|openshift-serverless\"}[$__range:15s])) * 0.000000277777777777778",
     "legendFormat": "serverless"
    },
    {
     "expr": "sum(increase(kepler_container_joules_total{container_namespace=~\"serverfull-ns|istio-system\"}[$__range:15s])) * 0.000000277777777777778",
     "legendFormat": "serverfull"
    }
   ]
  },
  {
   "title": "Real time Power consumption (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(kepler_container_core_joules_total{container_namespace=~\"serverless-ns|knative-serving|knative-serving-ingress|openshift-serverless|serverfull-ns|istio-system\"}[1m]))",
     "legendFormat": "CORE"
    },
    {
     "expr": "sum(rate(kepler_container_package_joules_total{container_namespace=~\"serverless-ns|knative-serving|knative-serving-ingress|openshift-serverless|serverfull-ns|istio-system\"}[1m]))",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum(rate(kepler_container_uncore_joules_total{container_namespace=~\"serverless-ns|knative-serving|knative-serving-ingress|openshift-serverless|serverfull-ns|istio-system\"}[1m]))",
     "legendFormat": "UNCORE"
    },
    {
     "expr": "sum(rate(kepler_container_dram_joules_total{container_namespace=~\"serverless-ns|knative-serving|knative-serving-ingress|openshift-serverless|serverfull-ns|istio-system\"}[1m]))",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum(rate(kepler_container_other_joules_total{container_namespace=~\"serverless-ns|knative-serving|knative-serving-ingress|openshift-serverless|serverfull-ns|istio-system\"}[1m]))",
     "legendFormat": "OTHER"
    }
   ]
  },
  {
   "title": "SUM of Serverless Total Energy Consumption (kWh)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(kepler_container_joules_total{container_namespace=~\"serverless-ns|knative-serving|knative-serving-ingress|openshift-serverless\"}[1h:15s])) * 0.000000277777777777778"
    }
   ]
  },
  {
   "title": "Top 10 Energy Consuming Namespaces (kWh) in Last 24 hours",
   "type": "bargauge",
   "description": "Total Power Consumption for Top 10 Namespaces (kWh per day)",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, kepler:kepler:container_joules_total:consumed:24h:by_ns) * $watt_per_second_to_kWh",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  }
 ]
}