apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.script.cm }}
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  traffic.json: |
    {
      "dns": "mock-mock-ns.apps.baremetal-cluster-jg.qe.devcluster.openshift.com",
      "port": "80",
      "timeout": 6000,
      "ranges": {
        "range_1": {
          "min": 0,
          "max": 999999
        }
      },
      "flow": [
        "post1",
        "post1"
      ],
      "messages": {
        "post1": {
          "method": "POST",
          "url": "url/example/path/id-<range_1>",
          "body": {
            "field1": "id-<range_1>-suffix",
            "field2": "some_stuff",
            "field3": {
              "sub_field1": 0,
              "subfield2": "some_string"
            }
          },
          "response": {
            "code": 200
          }
        },
        "get1": {
          "method": "GET",
          "url": "url/example/path?id=id-<range_1>",
          "response": {
            "code": 200
          }
        },
        "put1": {
          "method": "PUT",
          "url": "url/example/path/id-<range_1>",
          "body": {
            "some_key": 1
          },
          "response": {
            "code": 200
          }
        },
        "delete1": {
          "method": "DELETE",
          "url": "url/example/path/id-<range_1>",
          "body": {},
          "response": {
            "code": 200
          }
        },
        "wrong_path": {
          "method": "GET",
          "url": "url/example/wrong_path/id-<range_1>",
          "response": {
            "code": 400
          }
        },
        "timeout_example": {
          "method": "GET",
          "url": "url/timeout/id-<range_1>",
          "response": {
            "code": 200
          }
        },
        "error1": {
          "method": "GET",
          "url": "url/error/id-<range_1>",
          "response": {
            "code": 200
          }
        }
      }
    }


