apiVersion: v1
appVersion: "1.0"
description: Umbrella chart for hermes-job and opentelemtry collector to run in the same namespace as a knative function
name: kn-hermes
version: 0.0.1

dependencies:
  - name: hermes-job
    version: 0.0.1
    repository: https://jgomezselles.github.io/hermes-charts
    alias: hermesjob
