# Default values for serverfull deployment.

## Conditions for Chart dependencies
hermesjob:
  plain:
    enabled: true

## Global variables
global:
  istio:
    sidecar:
      inject: false
  hermes:
    endpoint: "server-mock"
    port: "8080"

## Values for this helm chart
replicaCount: 1
image:
## In case we want to overwrite images and force the cluster to download them
  pullPolicy: IfNotPresent
hermes:
  name: kn-hermes
