# Values for serverless deployment.

## Conditions for Chart dependencies
hermesjob:
  serverless:
    enabled: true
  server:
    enabled: false

global:
  hermes:
    endpoint: "serverless-mock.serverless-ns.svc.cluster.local"

## Values for this helm chart
image:
## In case we want to overwrite images and force the cluster to download them
  pullPolicy: IfNotPresent
