# Values for serverless deployment.

## Conditions for Chart dependencies
hermesjob:
  serverless:
    enabled: true
  server:
    enabled: false


## Global variables
global:
  istio:
    sidecar:
      inject: true
  hermes:
    endpoint: "serverless-mock.hermes.svc.cluster.local"
    port: "80"
    timeout: 6000
    metrics_endpoint: "otel-collector:4318/v1/metrics"
    repo: ghcr.io/jgomezselles/kubecon24/loadgen
    tag: 0.0.2
    cm: traffic-script-cm
    rate: 100
    print: 1
    time: 10

## Values for this helm chart
image:
## In case we want to overwrite images and force the cluster to download them
  pullPolicy: IfNotPresent

mock:
  image: ghcr.io/jgomezselles/kubecon24/server-mock:0.0.1

hermes:
  name: kn-hermes

replicaCount: 1

## Customizations for each dependency
hermesjob-server:
  schedule: "10 * * * *"

hermesjob-serverless:
  schedule: "10 * * * *"
