# Default values for hermes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

## Global variables
global:
  istio:
    sidecar:
      inject: false
  hermes:
    endpoint: "serverless-mock.hermes.svc.cluster.local"
    port: "80"
    timeout: 6000
    metrics_endpoint: "otel-collector:4318/v1/metrics"
    repo: ghcr.io/jgomezselles/kubecon24/loadgen
    tag: 0.0.2
    cm: traffic-script-cm
    rate: 2000
    print: 1
    time: 1200

## Values for this helm chart
image:
## In case we want to overwrite images and force the cluster to download them
  pullPolicy: IfNotPresent

hermes:
  name: kn-hermes

mock:
  name: server-mock
  image: ghcr.io/jgomezselles/kubecon24/server-mock:0.0.1
  pullPolicy: IfNotPresent
  replicaCount: 5
  resources: {}
  podAnnotations:
    sidecar.istio.io/inject: "true"
  service:
    port: 8080
    trype: ClusterIP

## Conditions for Chart dependencies
hermesjob:
  serverless:
    enabled: false
  server:
    enabled: false
  plain:
    enabled: false

## Customizations for each dependency
hermesjob-server:
  schedule: "1 * * * *"

hermesjob-serverless:
  schedule: "21 * * * *"

hermesjob-plain:
  schedule: "41 * * * *"
